service:
  golangci-lint-version: 1.23.x

run:
  deadline: 5m
  issues-exit-code: 1
  skip-files:
    - ".*_mock_test.go"

linters-settings:
  lll:
    line-length: 200
  misspell:
    locale: US
  gocyclo:
    min-complexity: 20
  wsl:
    allow-trailing-comment: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - errcheck
        - dupl
        - gosec
        - funlen
        - gomnd
    - linters:
        - stylecheck
        - golint
      source: "package (acme_client_manager|cert_manager|domain_checker)"

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - wsl
    - gomnd

